# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.7.10
loader_version=0.19.3
osl_version = 0.20.1

# Mod Properties
version=1.0.0
maven_group=net.nova.big_swords
mod_id=big_swords

# Dependencies
feather_build = 1
raven_build = 1
sparrow_build = 1
nests_build = 6