# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties

minecraft_version=26.2
minecraft_version_range=[26.2]

neo_version=26.2.0.0-beta

# Mod Properties

mod_id=big_swords
mod_name=Big Swords R
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.nova.big_swords
mod_authors=ImVeryBad, Foxirion
mod_description=Big Swords R is trying to bring back the nostalgia of the Asgard Shield mod for modern Minecraft, adding BIG swords, scythes, glaives and shields to the game with special stuff.